global:
    scrape_interval: 15s
    external_labels:
      monitor: 'user-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'cells'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.23.164:8000']
        labels:
          group: 'user'
